//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Savings.Exceptions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceErrorCodes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceErrorCodes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Savings.Exceptions.ResourceErrorCodes", typeof(ResourceErrorCodes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to amount.negative.
        /// </summary>
        public static string AMOUNT_ZERO_OR_NEGATIVE {
            get {
                return ResourceManager.GetString("AMOUNT_ZERO_OR_NEGATIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data.in-future.
        /// </summary>
        public static string DATE_IN_FUTURE {
            get {
                return ResourceManager.GetString("DATE_IN_FUTURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to expense-type.invalid.
        /// </summary>
        public static string EXPENSE_TYPE_INVALID {
            get {
                return ResourceManager.GetString("EXPENSE_TYPE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to final-date.before-initial.
        /// </summary>
        public static string FINAL_DATE_IN_PAST {
            get {
                return ResourceManager.GetString("FINAL_DATE_IN_PAST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page-number.negative.
        /// </summary>
        public static string PAGE_NUMBER_IS_NEGATIVE {
            get {
                return ResourceManager.GetString("PAGE_NUMBER_IS_NEGATIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page-size.negative.
        /// </summary>
        public static string PAGE_SIZE_IS_NEGATIVE {
            get {
                return ResourceManager.GetString("PAGE_SIZE_IS_NEGATIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page-size.too-long.
        /// </summary>
        public static string PAGE_SIZE_IS_TOO_LONG {
            get {
                return ResourceManager.GetString("PAGE_SIZE_IS_TOO_LONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search-term.too-short.
        /// </summary>
        public static string SEARCH_TERM_TOO_SHORT {
            get {
                return ResourceManager.GetString("SEARCH_TERM_TOO_SHORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to title.min-length-{MinLength}.
        /// </summary>
        public static string TITLE_MIN_LENGHT {
            get {
                return ResourceManager.GetString("TITLE_MIN_LENGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to title.required.
        /// </summary>
        public static string TITLE_REQUIRED {
            get {
                return ResourceManager.GetString("TITLE_REQUIRED", resourceCulture);
            }
        }
    }
}
